apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-tech-deploy
spec:
  selector:
    matchLabels:
      app: abc_deploy
  replicas: 3
  template:
    metadata:
      labels:
        app: abc_deploy
    spec:
      imagePullSecrets:             
      - name: regcred
      containers:
      - name: abc-app
        image: dokai5/abc_tech:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: abc-nodeport-svc
spec:
  selector:
    app: abc_deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
