---
- name: Install Docker on Jenkins
  hosts: docker_hosts
  become: yes
  tasks:
    - name: Install Docker
      package:
        name: docker
        state: present
    - name: Start Docker service
      service:
        name: docker
        state: started





